import type { ImageEntry } from "./types";

/**
 * Bild-Manifest — die einzige Liste aller Bilder der Seite.
 *
 * Es gibt aktuell KEINE Bilddateien im Projekt. Jeder Eintrag hier ist
 * zunächst ein Platzhalter. Der Alt-Text wird trotzdem JETZT final
 * geschrieben: dadurch ist der QC-Punkt „alle Bilder haben Alt-Texte"
 * erfüllt, bevor das erste Foto existiert, und beim Tausch ändert sich
 * am Markup nichts.
 *
 * Wenn Zoran ein Foto liefert:
 *   1. `npm run report` nennt Pfad und gewünschtes Motiv
 *   2. Datei unter public/slike/<id>.<jpg|webp|avif|png|svg> ablegen
 *   3. `npm run build`
 * Kein Code wird angefasst — src/lib/assets.ts findet die Datei selbst.
 *
 * `id` ist zugleich der Dateipfad. ASCII, keine Diakritika.
 *
 * `aspect` beschreibt den WUNSCH für den noch leeren Slot. Liegt eine Datei
 * vor, gewinnen deren echte Pixelmasse — der Wert hier muss also nicht
 * nachgezogen werden, wenn ein Foto in anderem Zuschnitt eintrifft.
 */
export const images = {
  /* ── Marke / Chrome ─────────────────────────────────────────────────── */
  /* Das Header-Logo. Die Datei heisst …-color.png und nicht sunward-logo.png,
     weil `Logo.tsx` sie explizit über diese ID zieht — die Auto-Discovery in
     src/lib/assets.ts greift also nicht versehentlich, und der Slot bleibt
     bewusst gesteuert.

     Zweite, hochauflösende Fassung von Zoran (Aug. 2026) ersetzt das
     alte 729×166-PNG. Die neue Rohdatei kam mit 1564×390 Leinwand und
     eigenem Rand-Padding — exakt dasselbe Muster wie beim Original, nur mit
     anderen Massen. Genauso behandelt: auf die Tinte beschnitten (Alpha-BBox
     über scripts/make-white-logos.py ermittelt, dann 1:1 auf die Farbdatei
     angewendet), jetzt 1515×342 = 4,43:1 statt 4,39:1 vorher — die
     Wortmarke selbst ist unverändert, nur das Padding drumherum war anders
     bemessen. `npm run make-white-logos` danach erneut gelaufen, damit die
     Weiss-Fassung von derselben, jetzt geschärften Quelle ausgeht. */
  "brand/sunward-logo-color": {
    id: "brand/sunward-logo-color",
    alt: "Sunward Hrvatska",
    hint: "Službeni Sunward Hrvatska logotip u boji (navy/crveno), po mogućnosti SVG",
    aspect: "1515/342",
    source: "sunward.eu",
    priority: true,
  },
  /* Bleibt offen: eine echte SVG-Fassung vom Hersteller. Die vorliegende
     PNG-Datei ist zwar seit Aug. 2026 höher aufgelöst (siehe oben), aber
     weiterhin Raster statt Vektor (PRD §489). */
  "brand/sunward-logo": {
    id: "brand/sunward-logo",
    alt: "Sunward logotip",
    hint: "Službeni Sunward logotip, po mogućnosti SVG s prozirnom pozadinom",
    aspect: "729/166",
    source: "sunward.eu",
  },
  /* Freigestellte Weiss-Fassungen für die türkise Markenfläche im Footer,
     erzeugt von scripts/make-white-logos.py. Die aspect-Werte sind die
     Pixelmasse der erzeugten Dateien — beim Sunward-Logo nach Beschnitt
     des Rand-Paddings, deshalb 1515/342 statt der 1564/390-Rohdatei. */
  "brand/sunward-logo-white": {
    id: "brand/sunward-logo-white",
    alt: "Sunward Hrvatska",
    aspect: "1515/342",
    hint: "Freigestellte Weiss-Fassung des Sunward-Hrvatska-Logos für den Footer — npm run make-white-logos",
    source: "sunward.eu",
  },
  /* Farbfassung fürs Partner-Badge im Header (PartnerBadge.tsx) — navy
     Parallelogramm mit weiss ausgespartem Schriftzug „HD Hidraulika
     Drvošped" und gelb-rotem Streifen rechts, echte Transparenz. NICHT im
     Footer verwendet: dort bleibt es bei -white (siehe
     scripts/make-white-logos.py-Kommentar, „Original ist navy und auf
     Türkis matschig" — gemessen 2,54:1 Navy-Körper bzw. 1,74:1 roter
     Streifen gegen --color-brand-deep, beides unter der 3:1-Schwelle für
     grafische Objekte). Auf der hellen Header-Utility-Leiste (#f5f6f7)
     dagegen unproblematisch: Navy 16,3:1, die Streifen sind dort
     Nebensache. */
  "brand/drvosped-logo-color": {
    id: "brand/drvosped-logo-color",
    alt: "Hidraulika Drvošped d.o.o.",
    aspect: "2371/327",
    hint: "Farbfassung des HD-Logos für das Partner-Badge im Header",
    source: "drvosped",
  },
  "brand/drvosped-logo-white": {
    id: "brand/drvosped-logo-white",
    alt: "Hidraulika Drvošped d.o.o.",
    aspect: "2371/327",
    hint: "Freigestellte Weiss-Fassung des HD-Logos für den Footer — npm run make-white-logos",
    source: "drvosped",
  },

  /* ── Startseite ─────────────────────────────────────────────────────── */
  "pocetna/hero": {
    id: "pocetna/hero",
    alt: "Sunward bager na gradilištu u Hrvatskoj",
    hint: "Široka fotografija Sunward bagera u radu — gradilište, dnevno svjetlo, mjesta za tekst s lijeve strane",
    aspect: "21/9",
    source: "zoran",
    priority: true,
    sizes: "100vw",
  },

  /* ── Kategorien (8) ─────────────────────────────────────────────────── */
  "kategorije/bageri/hero": {
    id: "kategorije/bageri/hero",
    alt: "Sunward bageri — pregled ponude za Hrvatsku",
    hint: "Više Sunward bagera zajedno ili jedan reprezentativan bager iz poluprofila",
    aspect: "21/9",
    source: "sunward.eu",
    sizes: "100vw",
  },
  "kategorije/utovarivaci/hero": {
    id: "kategorije/utovarivaci/hero",
    alt: "Sunward kompaktni utovarivači na radilištu",
    hint: "Sunward utovarivač u radu, po mogućnosti s punom lopatom",
    aspect: "21/9",
    source: "sunward.eu",
    sizes: "100vw",
  },
  "kategorije/zglobni-utovarivaci/hero": {
    id: "kategorije/zglobni-utovarivaci/hero",
    alt: "Sunward zglobni utovarivač",
    hint: "Zglobni utovarivač u radu, vidljiv zglob šasije",
    aspect: "21/9",
    source: "sunward.eu",
    sizes: "100vw",
  },
  "kategorije/busace-garniture/hero": {
    id: "kategorije/busace-garniture/hero",
    alt: "Sunward bušače garniture za temeljenje",
    hint: "Bušača garnitura s podignutim jarbolom na gradilištu",
    aspect: "21/9",
    source: "sunward.eu",
    sizes: "100vw",
  },
  "kategorije/zglobne-radne-platforme/hero": {
    id: "kategorije/zglobne-radne-platforme/hero",
    alt: "Sunward zglobne radne platforme",
    hint: "Zglobna platforma s izvučenom strelom",
    aspect: "21/9",
    source: "sunward.eu",
    sizes: "100vw",
  },
  "kategorije/skarasti-podizni-strojevi/hero": {
    id: "kategorije/skarasti-podizni-strojevi/hero",
    alt: "Sunward škarasti podizni strojevi",
    hint: "Škarasto dizalo s podignutom platformom",
    aspect: "21/9",
    source: "sunward.eu",
    sizes: "100vw",
  },
  "kategorije/teleskopske-dizalice/hero": {
    id: "kategorije/teleskopske-dizalice/hero",
    alt: "Sunward teleskopske dizalice",
    hint: "Gusjenična teleskopska dizalica s izvučenom strelom",
    aspect: "21/9",
    source: "sunward.eu",
    sizes: "100vw",
  },
  "kategorije/teleskopski-utovarivaci/hero": {
    id: "kategorije/teleskopski-utovarivaci/hero",
    alt: "Sunward teleskopski utovarivač",
    hint: "Teleskopski utovarivač s izvučenom strelom",
    aspect: "21/9",
    source: "sunward.eu",
    sizes: "100vw",
  },
  "kategorije/dodatna-oprema/hero": {
    id: "kategorije/dodatna-oprema/hero",
    alt: "Dodatna oprema i priključci za bagere",
    hint: "Više priključaka složenih zajedno ili bager s montiranim čekićem",
    aspect: "21/9",
    source: "zoran",
    sizes: "100vw",
  },

  /* ── Unterkategorie-Kacheln (9) ───────────────────────────────────────
     Freigestellte Icon-Illustrationen von sunward.eu/products/, quadratisch
     — bewusst ein anderes Seitenverhältnis als die 21/9-Kategorie-Heroes
     oben. Noch ohne UI-Konsument (CategoryBrowser.tsx zeigt Gruppen bisher
     nur als Text-Überschrift); dieser Eintrag liefert nur das Asset vor. */
  "kategorije/bageri/grupe/kotacni-bageri/tile": {
    id: "kategorije/bageri/grupe/kotacni-bageri/tile",
    alt: "Sunward kotačni bager — ilustracija",
    hint: "Freigestellte Sunward-Icon-Illustration für kotačne bagere (sunward.eu/products/)",
    aspect: "1/1",
    source: "sunward.eu",
  },
  "kategorije/bageri/grupe/mini-bageri/tile": {
    id: "kategorije/bageri/grupe/mini-bageri/tile",
    alt: "Sunward mini bager — ilustracija",
    hint: "Freigestellte Sunward-Icon-Illustration für mini bagere (sunward.eu/products/)",
    aspect: "1/1",
    source: "sunward.eu",
  },
  "kategorije/bageri/grupe/kompaktni-bageri/tile": {
    id: "kategorije/bageri/grupe/kompaktni-bageri/tile",
    alt: "Sunward kompaktni bager — ilustracija",
    hint: "Freigestellte Sunward-Icon-Illustration für kompaktne bagere (sunward.eu/products/)",
    aspect: "1/1",
    source: "sunward.eu",
  },
  "kategorije/bageri/grupe/srednji-bageri/tile": {
    id: "kategorije/bageri/grupe/srednji-bageri/tile",
    alt: "Sunward srednji bager — ilustracija",
    hint: "Freigestellte Sunward-Icon-Illustration für srednje bagere (sunward.eu/products/)",
    aspect: "1/1",
    source: "sunward.eu",
  },
  "kategorije/bageri/grupe/veliki-bageri/tile": {
    id: "kategorije/bageri/grupe/veliki-bageri/tile",
    alt: "Sunward veliki bager — ilustracija",
    hint: "Freigestellte Sunward-Icon-Illustration für velike bagere (sunward.eu/products/)",
    aspect: "1/1",
    source: "sunward.eu",
  },
  "kategorije/utovarivaci/grupe/gusjenicni-utovarivaci/tile": {
    id: "kategorije/utovarivaci/grupe/gusjenicni-utovarivaci/tile",
    alt: "Sunward gusjenični utovarivač — ilustracija",
    hint: "Freigestellte Sunward-Icon-Illustration für gusjenične utovarivače (sunward.eu/products/)",
    aspect: "1/1",
    source: "sunward.eu",
  },
  "kategorije/utovarivaci/grupe/kotacni-mini-utovarivaci/tile": {
    id: "kategorije/utovarivaci/grupe/kotacni-mini-utovarivaci/tile",
    alt: "Sunward kotačni mini utovarivač — ilustracija",
    hint: "Freigestellte Sunward-Icon-Illustration für kotačne mini utovarivače (sunward.eu/products/)",
    aspect: "1/1",
    source: "sunward.eu",
  },
  "kategorije/skarasti-podizni-strojevi/grupe/skarasti-elektricni/tile": {
    id: "kategorije/skarasti-podizni-strojevi/grupe/skarasti-elektricni/tile",
    alt: "Sunward električno škarasto dizalo — ilustracija",
    hint: "Freigestellte Sunward-Icon-Illustration für električne škarasti podizne strojeve (sunward.eu/products/)",
    aspect: "1/1",
    source: "sunward.eu",
  },
  "kategorije/skarasti-podizni-strojevi/grupe/skarasti-terenski/tile": {
    id: "kategorije/skarasti-podizni-strojevi/grupe/skarasti-terenski/tile",
    alt: "Sunward terensko škarasto dizalo — ilustracija",
    hint: "Freigestellte Sunward-Icon-Illustration für terenske škarasti podizne strojeve (sunward.eu/products/)",
    aspect: "1/1",
    source: "sunward.eu",
  },

  /* ── Modelle (51) ───────────────────────────────────────────────────── */
  "proizvodi/swe08f/glavna": {
    id: "proizvodi/swe08f/glavna",
    alt: "Sunward SWE 08F bager — pogled s prednje lijeve strane",
    hint: "SWE 08F, cijeli stroj, prednji lijevi kut, ruka spuštena, gradilište ili neutralna pozadina",
    aspect: "4/3",
    source: "sunward.eu",
    altTemplate: "Sunward SWE 08F bager — fotografija {n}",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "proizvodi/swe10fe/glavna": {
    id: "proizvodi/swe10fe/glavna",
    alt: "Sunward SWE 10FE bager — pogled s prednje lijeve strane",
    hint: "SWE 10FE, cijeli stroj, prednji lijevi kut, ruka spuštena, gradilište ili neutralna pozadina",
    aspect: "4/3",
    source: "sunward.eu",
    altTemplate: "Sunward SWE 10FE bager — fotografija {n}",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "proizvodi/swe18uf/glavna": {
    id: "proizvodi/swe18uf/glavna",
    alt: "Sunward SWE 18UF bager — pogled s prednje lijeve strane",
    hint: "SWE 18UF, cijeli stroj, prednji lijevi kut, ruka spuštena, gradilište ili neutralna pozadina",
    aspect: "4/3",
    source: "sunward.eu",
    altTemplate: "Sunward SWE 18UF bager — fotografija {n}",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "proizvodi/swe20f-1/glavna": {
    id: "proizvodi/swe20f-1/glavna",
    alt: "Sunward SWE 20F-1 bager — pogled s prednje lijeve strane",
    hint: "SWE 20F-1, cijeli stroj, prednji lijevi kut, ruka spuštena, gradilište ili neutralna pozadina",
    aspect: "4/3",
    source: "sunward.eu",
    altTemplate: "Sunward SWE 20F-1 bager — fotografija {n}",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "proizvodi/swe20fe/glavna": {
    id: "proizvodi/swe20fe/glavna",
    alt: "Sunward SWE 20FE bager — pogled s prednje lijeve strane",
    hint: "SWE 20FE, cijeli stroj, prednji lijevi kut, ruka spuštena, gradilište ili neutralna pozadina",
    aspect: "4/3",
    source: "sunward.eu",
    altTemplate: "Sunward SWE 20FE bager — fotografija {n}",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "proizvodi/swe25uf/glavna": {
    id: "proizvodi/swe25uf/glavna",
    alt: "Sunward SWE 25UF bager — pogled s prednje lijeve strane",
    hint: "SWE 25UF, cijeli stroj, prednji lijevi kut, ruka spuštena, gradilište ili neutralna pozadina",
    aspect: "4/3",
    source: "sunward.eu",
    altTemplate: "Sunward SWE 25UF bager — fotografija {n}",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "proizvodi/swe35uf/glavna": {
    id: "proizvodi/swe35uf/glavna",
    alt: "Sunward SWE 35UF bager — pogled s prednje lijeve strane",
    hint: "SWE 35UF, cijeli stroj, prednji lijevi kut, ruka spuštena, gradilište ili neutralna pozadina",
    aspect: "4/3",
    source: "sunward.eu",
    altTemplate: "Sunward SWE 35UF bager — fotografija {n}",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "proizvodi/swe50uf/glavna": {
    id: "proizvodi/swe50uf/glavna",
    alt: "Sunward SWE 50UF bager — pogled s prednje lijeve strane",
    hint: "SWE 50UF, cijeli stroj, prednji lijevi kut, ruka spuštena, gradilište ili neutralna pozadina",
    aspect: "4/3",
    source: "sunward.eu",
    altTemplate: "Sunward SWE 50UF bager — fotografija {n}",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "proizvodi/swe60uf/glavna": {
    id: "proizvodi/swe60uf/glavna",
    alt: "Sunward SWE 60UF bager — pogled s prednje lijeve strane",
    hint: "SWE 60UF, cijeli stroj, prednji lijevi kut, ruka spuštena, gradilište ili neutralna pozadina",
    aspect: "4/3",
    source: "sunward.eu",
    altTemplate: "Sunward SWE 60UF bager — fotografija {n}",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "proizvodi/swe90uf/glavna": {
    id: "proizvodi/swe90uf/glavna",
    alt: "Sunward SWE 90UF bager — pogled s prednje lijeve strane",
    hint: "SWE 90UF, cijeli stroj, prednji lijevi kut, ruka spuštena, gradilište ili neutralna pozadina",
    aspect: "4/3",
    source: "sunward.eu",
    altTemplate: "Sunward SWE 90UF bager — fotografija {n}",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "proizvodi/swe90uf-2pb/glavna": {
    id: "proizvodi/swe90uf-2pb/glavna",
    alt: "Sunward SWE 90UF-2PB bager — pogled s prednje lijeve strane",
    hint: "SWE 90UF-2PB, cijeli stroj, prednji lijevi kut, ruka spuštena, gradilište ili neutralna pozadina",
    aspect: "4/3",
    source: "sunward.eu",
    altTemplate: "Sunward SWE 90UF-2PB bager — fotografija {n}",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "proizvodi/swe155f/glavna": {
    id: "proizvodi/swe155f/glavna",
    alt: "Sunward SWE 155F bager — pogled s prednje lijeve strane",
    hint: "SWE 155F, cijeli stroj, prednji lijevi kut, ruka spuštena, gradilište ili neutralna pozadina",
    aspect: "4/3",
    source: "sunward.eu",
    altTemplate: "Sunward SWE 155F bager — fotografija {n}",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  /* SWE 155F-5 / SWE 155F-5A: kein sunward.eu-Eintrag (Modell wird dort
     noch nicht geführt) — Foto kommt direkt von Zoran, kein Fetch möglich. */
  "proizvodi/swe155f-5/glavna": {
    id: "proizvodi/swe155f-5/glavna",
    alt: "Sunward SWE 155F-5 bager — pogled s prednje lijeve strane",
    hint: "SWE 155F-5, cijeli stroj, prednji lijevi kut, ruka spuštena, gradilište ili neutralna pozadina — foto dostavlja Zoran, model nije na sunward.eu",
    aspect: "4/3",
    source: "zoran",
    altTemplate: "Sunward SWE 155F-5 bager — fotografija {n}",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "proizvodi/swe155f-5a/glavna": {
    id: "proizvodi/swe155f-5a/glavna",
    alt: "Sunward SWE 155F-5A bager — pogled s prednje lijeve strane",
    hint: "SWE 155F-5A, cijeli stroj, prednji lijevi kut, ruka spuštena, gradilište ili neutralna pozadina — foto dostavlja Zoran, model nije na sunward.eu",
    aspect: "4/3",
    source: "zoran",
    altTemplate: "Sunward SWE 155F-5A bager — fotografija {n}",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "proizvodi/swe155uf/glavna": {
    id: "proizvodi/swe155uf/glavna",
    alt: "Sunward SWE 155UF bager — pogled s prednje lijeve strane",
    hint: "SWE 155UF, cijeli stroj, prednji lijevi kut, ruka spuštena, gradilište ili neutralna pozadina",
    aspect: "4/3",
    source: "sunward.eu",
    altTemplate: "Sunward SWE 155UF bager — fotografija {n}",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "proizvodi/swe155uf-2pb/glavna": {
    id: "proizvodi/swe155uf-2pb/glavna",
    alt: "Sunward SWE 155UF-2PB bager — pogled s prednje lijeve strane",
    hint: "SWE 155UF-2PB, cijeli stroj, prednji lijevi kut, ruka spuštena, gradilište ili neutralna pozadina",
    aspect: "4/3",
    source: "sunward.eu",
    altTemplate: "Sunward SWE 155UF-2PB bager — fotografija {n}",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "proizvodi/swe155fw/glavna": {
    id: "proizvodi/swe155fw/glavna",
    alt: "Sunward SWE 155FW bager — pogled s prednje lijeve strane",
    hint: "SWE 155FW, cijeli stroj, prednji lijevi kut, ruka spuštena, gradilište ili neutralna pozadina",
    aspect: "4/3",
    source: "sunward.eu",
    altTemplate: "Sunward SWE 155FW bager — fotografija {n}",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "proizvodi/swe215f-5a/glavna": {
    id: "proizvodi/swe215f-5a/glavna",
    alt: "Sunward SWE 215F-5A bager — pogled s prednje lijeve strane",
    hint: "SWE 215F-5A, cijeli stroj, prednji lijevi kut, ruka spuštena, gradilište ili neutralna pozadina",
    aspect: "4/3",
    source: "sunward.eu",
    altTemplate: "Sunward SWE 215F-5A bager — fotografija {n}",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "proizvodi/swe225fn/glavna": {
    id: "proizvodi/swe225fn/glavna",
    alt: "Sunward SWE 225FN bager — pogled s prednje lijeve strane",
    hint: "SWE 225FN, cijeli stroj, prednji lijevi kut, ruka spuštena, gradilište ili neutralna pozadina",
    aspect: "4/3",
    source: "sunward.eu",
    altTemplate: "Sunward SWE 225FN bager — fotografija {n}",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "proizvodi/swe240fe/glavna": {
    id: "proizvodi/swe240fe/glavna",
    alt: "Sunward SWE 240FE bager — pogled s prednje lijeve strane",
    hint: "SWE 240FE, cijeli stroj, prednji lijevi kut, ruka spuštena, gradilište ili neutralna pozadina",
    aspect: "4/3",
    source: "sunward.eu",
    altTemplate: "Sunward SWE 240FE bager — fotografija {n}",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "proizvodi/swe335f-5/glavna": {
    id: "proizvodi/swe335f-5/glavna",
    alt: "Sunward SWE 335F-5 bager — pogled s prednje lijeve strane",
    hint: "SWE 335F-5, cijeli stroj, prednji lijevi kut, ruka spuštena, gradilište ili neutralna pozadina",
    aspect: "4/3",
    source: "sunward.eu",
    altTemplate: "Sunward SWE 335F-5 bager — fotografija {n}",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "proizvodi/swtl4538/glavna": {
    id: "proizvodi/swtl4538/glavna",
    alt: "Sunward SWTL 4538 utovarivač — pogled s prednje lijeve strane",
    hint: "SWTL 4538, cijeli stroj iz poluprofila, lopata spuštena na tlo",
    aspect: "4/3",
    source: "sunward.eu",
    altTemplate: "Sunward SWTL 4538 utovarivač — fotografija {n}",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "proizvodi/swtl5238/glavna": {
    id: "proizvodi/swtl5238/glavna",
    alt: "Sunward SWTL 5238 utovarivač — pogled s prednje lijeve strane",
    hint: "SWTL 5238, cijeli stroj iz poluprofila, lopata spuštena na tlo",
    aspect: "4/3",
    source: "sunward.eu",
    altTemplate: "Sunward SWTL 5238 utovarivač — fotografija {n}",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "proizvodi/swl2830/glavna": {
    id: "proizvodi/swl2830/glavna",
    alt: "Sunward SWL 2830 utovarivač — pogled s prednje lijeve strane",
    hint: "SWL 2830, cijeli stroj iz poluprofila, lopata spuštena na tlo",
    aspect: "4/3",
    source: "sunward.eu",
    altTemplate: "Sunward SWL 2830 utovarivač — fotografija {n}",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "proizvodi/swl3230/glavna": {
    id: "proizvodi/swl3230/glavna",
    alt: "Sunward SWL 3230 utovarivač — pogled s prednje lijeve strane",
    hint: "SWL 3230, cijeli stroj iz poluprofila, lopata spuštena na tlo",
    aspect: "4/3",
    source: "sunward.eu",
    altTemplate: "Sunward SWL 3230 utovarivač — fotografija {n}",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "proizvodi/swl4038/glavna": {
    id: "proizvodi/swl4038/glavna",
    alt: "Sunward SWL 4038 utovarivač — pogled s prednje lijeve strane",
    hint: "SWL 4038, cijeli stroj iz poluprofila, lopata spuštena na tlo",
    aspect: "4/3",
    source: "sunward.eu",
    altTemplate: "Sunward SWL 4038 utovarivač — fotografija {n}",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "proizvodi/sl06w/glavna": {
    id: "proizvodi/sl06w/glavna",
    alt: "Sunward SL 06W zglobni utovarivač — pogled s prednje lijeve strane",
    hint: "SL 06W, cijeli stroj iz poluprofila, vidljiv zglob šasije",
    aspect: "4/3",
    source: "sunward.eu",
    altTemplate: "Sunward SL 06W zglobni utovarivač — fotografija {n}",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "proizvodi/sl12w/glavna": {
    id: "proizvodi/sl12w/glavna",
    alt: "Sunward SL 12W zglobni utovarivač — pogled s prednje lijeve strane",
    hint: "SL 12W, cijeli stroj iz poluprofila, vidljiv zglob šasije",
    aspect: "4/3",
    source: "sunward.eu",
    altTemplate: "Sunward SL 12W zglobni utovarivač — fotografija {n}",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "proizvodi/swdm85/glavna": {
    id: "proizvodi/swdm85/glavna",
    alt: "Sunward SWDM 85 bušača garnitura — pogled s prednje lijeve strane",
    hint: "SWDM 85, garnitura u radnom položaju s podignutim jarbolom",
    aspect: "4/3",
    source: "sunward.eu",
    altTemplate: "Sunward SWDM 85 bušača garnitura — fotografija {n}",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "proizvodi/swdm135/glavna": {
    id: "proizvodi/swdm135/glavna",
    alt: "Sunward SWDM 135 bušača garnitura — pogled s prednje lijeve strane",
    hint: "SWDM 135, garnitura u radnom položaju s podignutim jarbolom",
    aspect: "4/3",
    source: "sunward.eu",
    altTemplate: "Sunward SWDM 135 bušača garnitura — fotografija {n}",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "proizvodi/swdm165s/glavna": {
    id: "proizvodi/swdm165s/glavna",
    alt: "Sunward SWDM 165S bušača garnitura — pogled s prednje lijeve strane",
    hint: "SWDM 165S, garnitura u radnom položaju s podignutim jarbolom",
    aspect: "4/3",
    source: "sunward.eu",
    altTemplate: "Sunward SWDM 165S bušača garnitura — fotografija {n}",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "proizvodi/swdm215s/glavna": {
    id: "proizvodi/swdm215s/glavna",
    alt: "Sunward SWDM 215S bušača garnitura — pogled s prednje lijeve strane",
    hint: "SWDM 215S, garnitura u radnom položaju s podignutim jarbolom",
    aspect: "4/3",
    source: "sunward.eu",
    altTemplate: "Sunward SWDM 215S bušača garnitura — fotografija {n}",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "proizvodi/swdm245/glavna": {
    id: "proizvodi/swdm245/glavna",
    alt: "Sunward SWDM 245 bušača garnitura — pogled s prednje lijeve strane",
    hint: "SWDM 245, garnitura u radnom položaju s podignutim jarbolom",
    aspect: "4/3",
    source: "sunward.eu",
    altTemplate: "Sunward SWDM 245 bušača garnitura — fotografija {n}",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "proizvodi/swdm325/glavna": {
    id: "proizvodi/swdm325/glavna",
    alt: "Sunward SWDM 325 bušača garnitura — pogled s prednje lijeve strane",
    hint: "SWDM 325, garnitura u radnom položaju s podignutim jarbolom",
    aspect: "4/3",
    source: "sunward.eu",
    altTemplate: "Sunward SWDM 325 bušača garnitura — fotografija {n}",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "proizvodi/swdm415/glavna": {
    id: "proizvodi/swdm415/glavna",
    alt: "Sunward SWDM 415 bušača garnitura — pogled s prednje lijeve strane",
    hint: "SWDM 415, garnitura u radnom položaju s podignutim jarbolom",
    aspect: "4/3",
    source: "sunward.eu",
    altTemplate: "Sunward SWDM 415 bušača garnitura — fotografija {n}",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "proizvodi/swa16j/glavna": {
    id: "proizvodi/swa16j/glavna",
    alt: "Sunward SWA 16J zglobna radna platforma — pogled s prednje lijeve strane",
    hint: "SWA 16J, platforma s djelomično izvučenom zglobnom strelom",
    aspect: "4/3",
    source: "sunward.eu",
    altTemplate: "Sunward SWA 16J zglobna radna platforma — fotografija {n}",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "proizvodi/swa16je/glavna": {
    id: "proizvodi/swa16je/glavna",
    alt: "Sunward SWA 16JE zglobna radna platforma — pogled s prednje lijeve strane",
    hint: "SWA 16JE, platforma s djelomično izvučenom zglobnom strelom",
    aspect: "4/3",
    source: "sunward.eu",
    altTemplate: "Sunward SWA 16JE zglobna radna platforma — fotografija {n}",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "proizvodi/swa18je-p/glavna": {
    id: "proizvodi/swa18je-p/glavna",
    alt: "Sunward SWA 18JE-P zglobna radna platforma — pogled s prednje lijeve strane",
    hint: "SWA 18JE-P, platforma s djelomično izvučenom zglobnom strelom",
    aspect: "4/3",
    source: "sunward.eu",
    altTemplate: "Sunward SWA 18JE-P zglobna radna platforma — fotografija {n}",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "proizvodi/swa22je-p/glavna": {
    id: "proizvodi/swa22je-p/glavna",
    alt: "Sunward SWA 22JE-P zglobna radna platforma — pogled s prednje lijeve strane",
    hint: "SWA 22JE-P, platforma s djelomično izvučenom zglobnom strelom",
    aspect: "4/3",
    source: "sunward.eu",
    altTemplate: "Sunward SWA 22JE-P zglobna radna platforma — fotografija {n}",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "proizvodi/swsl0607dc-s/glavna": {
    id: "proizvodi/swsl0607dc-s/glavna",
    alt: "Sunward SWSL 0607DC-S škarasti podizni stroj — pogled s prednje lijeve strane",
    hint: "SWSL 0607DC-S, stroj s podignutom platformom, bočni ili poluprofil",
    aspect: "4/3",
    source: "sunward.eu",
    altTemplate: "Sunward SWSL 0607DC-S škarasti podizni stroj — fotografija {n}",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "proizvodi/swsl0607dc/glavna": {
    id: "proizvodi/swsl0607dc/glavna",
    alt: "Sunward SWSL 0607DC škarasti podizni stroj — pogled s prednje lijeve strane",
    hint: "SWSL 0607DC, stroj s podignutom platformom, bočni ili poluprofil",
    aspect: "4/3",
    source: "sunward.eu",
    altTemplate: "Sunward SWSL 0607DC škarasti podizni stroj — fotografija {n}",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "proizvodi/swsl0807dc/glavna": {
    id: "proizvodi/swsl0807dc/glavna",
    alt: "Sunward SWSL 0807DC škarasti podizni stroj — pogled s prednje lijeve strane",
    hint: "SWSL 0807DC, stroj s podignutom platformom, bočni ili poluprofil",
    aspect: "4/3",
    source: "sunward.eu",
    altTemplate: "Sunward SWSL 0807DC škarasti podizni stroj — fotografija {n}",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "proizvodi/swsl1008dc/glavna": {
    id: "proizvodi/swsl1008dc/glavna",
    alt: "Sunward SWSL 1008DC škarasti podizni stroj — pogled s prednje lijeve strane",
    hint: "SWSL 1008DC, stroj s podignutom platformom, bočni ili poluprofil",
    aspect: "4/3",
    source: "sunward.eu",
    altTemplate: "Sunward SWSL 1008DC škarasti podizni stroj — fotografija {n}",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "proizvodi/swsl1212dc/glavna": {
    id: "proizvodi/swsl1212dc/glavna",
    alt: "Sunward SWSL 1212DC škarasti podizni stroj — pogled s prednje lijeve strane",
    hint: "SWSL 1212DC, stroj s podignutom platformom, bočni ili poluprofil",
    aspect: "4/3",
    source: "sunward.eu",
    altTemplate: "Sunward SWSL 1212DC škarasti podizni stroj — fotografija {n}",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "proizvodi/swsl1412dc/glavna": {
    id: "proizvodi/swsl1412dc/glavna",
    alt: "Sunward SWSL 1412DC škarasti podizni stroj — pogled s prednje lijeve strane",
    hint: "SWSL 1412DC, stroj s podignutom platformom, bočni ili poluprofil",
    aspect: "4/3",
    source: "sunward.eu",
    altTemplate: "Sunward SWSL 1412DC škarasti podizni stroj — fotografija {n}",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "proizvodi/swsl1223rt/glavna": {
    id: "proizvodi/swsl1223rt/glavna",
    alt: "Sunward SWSL 1223RT škarasti podizni stroj — pogled s prednje lijeve strane",
    hint: "SWSL 1223RT, stroj s podignutom platformom, bočni ili poluprofil",
    aspect: "4/3",
    source: "sunward.eu",
    altTemplate: "Sunward SWSL 1223RT škarasti podizni stroj — fotografija {n}",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "proizvodi/swsl1623rt/glavna": {
    id: "proizvodi/swsl1623rt/glavna",
    alt: "Sunward SWSL 1623RT škarasti podizni stroj — pogled s prednje lijeve strane",
    hint: "SWSL 1623RT, stroj s podignutom platformom, bočni ili poluprofil",
    aspect: "4/3",
    source: "sunward.eu",
    altTemplate: "Sunward SWSL 1623RT škarasti podizni stroj — fotografija {n}",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "proizvodi/swsl2023rt/glavna": {
    id: "proizvodi/swsl2023rt/glavna",
    alt: "Sunward SWSL 2023RT škarasti podizni stroj — pogled s prednje lijeve strane",
    hint: "SWSL 2023RT, stroj s podignutom platformom, bočni ili poluprofil",
    aspect: "4/3",
    source: "sunward.eu",
    altTemplate: "Sunward SWSL 2023RT škarasti podizni stroj — fotografija {n}",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "proizvodi/swtc5d/glavna": {
    id: "proizvodi/swtc5d/glavna",
    alt: "Sunward SWTC 5D teleskopska dizalica — pogled s prednje lijeve strane",
    hint: "SWTC 5D, dizalica s izvučenom teleskopskom strelom",
    aspect: "4/3",
    source: "sunward.eu",
    altTemplate: "Sunward SWTC 5D teleskopska dizalica — fotografija {n}",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "proizvodi/swtc10/glavna": {
    id: "proizvodi/swtc10/glavna",
    alt: "Sunward SWTC 10 teleskopska dizalica — pogled s prednje lijeve strane",
    hint: "SWTC 10, dizalica s izvučenom teleskopskom strelom",
    aspect: "4/3",
    source: "sunward.eu",
    altTemplate: "Sunward SWTC 10 teleskopska dizalica — fotografija {n}",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "proizvodi/swth3507/glavna": {
    id: "proizvodi/swth3507/glavna",
    alt: "Sunward SWTH 3507 teleskopski utovarivač — pogled s prednje lijeve strane",
    hint: "SWTH 3507, stroj s izvučenom strelom i vilicama",
    aspect: "4/3",
    source: "sunward.eu",
    altTemplate: "Sunward SWTH 3507 teleskopski utovarivač — fotografija {n}",
    sizes: "(max-width: 768px) 100vw, 640px",
  },

  /* ── Dodatna oprema ─────────────────────────────────────────────────── */
  "oprema/hidraulicki-cekic/glavna": {
    id: "oprema/hidraulicki-cekic/glavna",
    alt: "Hidraulički čekić za bager — priključak za rušenje i stijenu",
    hint: "Hidraulički čekić montiran na bager ili samostalno na paleti",
    aspect: "4/3",
    source: "zoran",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "oprema/thumb/glavna": {
    id: "oprema/thumb/glavna",
    alt: "Thumb za bager — hidraulička hvataljka za prihvat materijala",
    hint: "Thumb montiran uz žlicu bagera, u otvorenom položaju",
    aspect: "4/3",
    source: "zoran",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "oprema/sumske-skare/glavna": {
    id: "oprema/sumske-skare/glavna",
    alt: "Šumske škare za bager — priključak za rezanje stabala i grmlja",
    hint: "Šumske škare montirane na bager, u radu na sječi",
    aspect: "4/3",
    source: "zoran",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "oprema/busac-rupa/glavna": {
    id: "oprema/busac-rupa/glavna",
    alt: "Bušač rupa (svrdlo) za bager — priključak za bušenje rupa u zemlji",
    hint: "Svrdlo za bušenje rupa montirano na bager",
    aspect: "4/3",
    source: "zoran",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "oprema/roto-tilt/glavna": {
    id: "oprema/roto-tilt/glavna",
    alt: "Roto tilt za bager — priključak za zakretanje i nagib žlice",
    hint: "Roto tilt montiran između bagera i žlice",
    aspect: "4/3",
    source: "zoran",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "oprema/power-tilt/glavna": {
    id: "oprema/power-tilt/glavna",
    alt: "Power tilt za bager — priključak za nagib žlice",
    hint: "Power tilt montiran između bagera i žlice",
    aspect: "4/3",
    source: "zoran",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "oprema/vilice-za-bager/glavna": {
    id: "oprema/vilice-za-bager/glavna",
    alt: "Vilice za bager — priključak za prijenos paleta i materijala",
    hint: "Vilice montirane na bager umjesto žlice",
    aspect: "4/3",
    source: "zoran",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "oprema/sortirne-skare/glavna": {
    id: "oprema/sortirne-skare/glavna",
    alt: "Sortirne škare za bager — priključak za sortiranje građevinskog otpada",
    hint: "Sortirne škare montirane na bager, u radu na gradilištu",
    aspect: "4/3",
    source: "zoran",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "oprema/mulcer/glavna": {
    id: "oprema/mulcer/glavna",
    alt: "Mulčer za bager — priključak za usitnjavanje grmlja i niskog rastinja",
    hint: "Mulčer montiran na bager, u radu na čišćenju terena",
    aspect: "4/3",
    source: "zoran",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
  "oprema/mjesalica-betona/glavna": {
    id: "oprema/mjesalica-betona/glavna",
    alt: "Mješalica betona za bager — priključak za miješanje betona na gradilištu",
    hint: "Mješalica betona montirana na bager umjesto žlice",
    aspect: "4/3",
    source: "zoran",
    sizes: "(max-width: 768px) 100vw, 640px",
  },
} as const satisfies Record<string, ImageEntry>;
